### ISSUE TITLE
extract spectrum from elliptical region

### ISSUE THREAD

**Issue by kimager** [astrofle/CRRLpy#4]
extractspec.py, extracting spectrum from an elliptical aperture is currently not supported

**Comment by astrofle** [comment]
Did you try creating the elliptical aperture in CASA, exporting it as a casa region file and then using that as input?
extractspec.py should be able to handle casa region files.

**Comment by kimager** [comment]
Oh no I looked in the code but didn’t catch that. Could you provide an example of the input?

**Comment by astrofle** [comment]
extractspec.py fits_file.fits crtf,none,none,your_casa_region_file.crtf output.txt

However, it is extremely slow. I'll add support for an elliptical region.

**Comment by kimager** [comment]
note, an ellipse with position angle of 0 or 90 deg is currently only supported for casa regions.

**Comment by astrofle** [comment]
Took a while, but it is implemented now. Let me know if you find anything strange.
