### ISSUE TITLE
reference to undefined (log) variable in extractspec.py

### ISSUE THREAD

**Issue by kimager** [astrofle/CRRLpy#5]
There are two instances to:
NameError: global name 'mod_log' is not defined
in extractspec.py

**Comment by astrofle** [comment]
I could not find references to 'mod_log' in extractspec.py
Could you please include the code that produces the error.

**Comment by kimager** [comment]
My apologies. I received the error when running extractspec.py, but the functions containing the undefined variable are in imtools.py. (Let me know if you still can't find it and I'll try to reproduce it.)

**Comment by astrofle** [comment]
fixed
