### ISSUE TITLE
handle icrs coordinates in extractspec.py

### ISSUE THREAD

**Issue by kimager** [astrofle/CRRLpy#6]
would be useful if extractspec.py could handle ICRS coordinates for input sky coordinates (in addition to the fk4,fk5 currently supported)

**Comment by astrofle** [comment]
Added support for ICRS coordinates (I think in practice, for now, they are the same as fk5).

**Comment by kimager** [comment]
Oh great, thanks!
There is a slight offset (on the order of 0.01’’) between FK5 and ICRS (which is relevant for the high-resolution work I’m doing now).
