### ISSUE TITLE
extractspec.py output frequency is off

### ISSUE THREAD

**Issue by kimager** [astrofle/CRRLpy#7]
The header of my files reads:
CTYPE3  = 'FREQ    '                     /Axis name                             
CRPIX3  =      1.0000000000000           /Reference pixel                       
CRVAL3  =      2303250000.0000           /Reference value                       
CDELT3  =      56000000.000000           /Pixel increment                       
CROTA3  =      0.0000000000000 

The frequency extracted should be centered on 2.30325 GHz, but the output from extractspec is 2.24725 GHz when calling it in a script with
extractspec.main(outfile, image, region, 'flux', False, None, 3, False)

Note I also find the same error for extracting spectra from cubes.

**Comment by astrofle** [comment]
Now extractspec uses astropy to compute the axes coordinates. Now for the example you provided the returned value is 2.3032500e+09 (Hz).
