### ISSUE TITLE
deprecated astropy module

### ISSUE THREAD

**Issue by kimager** [astrofle/CRRLpy#8]
astropy.modeling.blackbody module deprecated since astropy v4.0

**Comment by kimager** [comment]
used in rrlmod.py

**Comment by kimager** [comment]
from astropy.modeling.models import BlackBody
# default results from BlackBody same units as blackbody_nu
bb_nu = BlackBody(temperature)

**Comment by astrofle** [comment]
This has been updated to use the current equivalent class ([BlackBody](https://docs.astropy.org/en/stable/api/astropy.modeling.physical_models.BlackBody.html)).
